var OA_output = new Array(); 
OA_output['1'] = '';
OA_output['1'] += "<"+"script async src=\"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['1'] += "<"+"!-- 侧栏矩形 -->\n";
OA_output['1'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['1'] += "style=\"display:inline-block;width:300px;height:250px\"\n";
OA_output['1'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['1'] += "data-ad-slot=\"9674628595\"><"+"/ins>\n";
OA_output['1'] += "<"+"script>\n";
OA_output['1'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['1'] += "<"+"/script><"+"div id=\'beacon_5b5dff7962\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=202&amp;campaignid=1&amp;zoneid=1&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=5b5dff7962\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['2'] = '';
OA_output['2'] += "<"+"div style=\"line-height: 0; background: #FAFAFA\">\n";
OA_output['2'] += "<"+"div class=\"container text-center\" style=\"position: relative;\">\n";
OA_output['2'] += "<"+"!--<"+"a href=\"https://segmentfault.com/user/login\" class=\"small text-muted\" style=\"position: absolute; top: 10px; right: 15px;\">登录免广告<"+"/a>--><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['2'] += "<"+"!-- 导航下横幅广告（大型） -->\n";
OA_output['2'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['2'] += "style=\"display:inline-block;width:970px;height:90px\"\n";
OA_output['2'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['2'] += "data-ad-slot=\"6450634185\"><"+"/ins>\n";
OA_output['2'] += "<"+"script>\n";
OA_output['2'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['2'] += "<"+"/script><"+"div id=\'beacon_5d360ad241\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=43&amp;campaignid=1&amp;zoneid=2&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=5d360ad241\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['2'] += "<"+"/div>\n";
OA_output['3'] = '';
OA_output['3'] += "<"+"div style=\"text-align: center; line-height: 0\"><"+"script async src=\"//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js\"><"+"/script>\n";
OA_output['3'] += "<"+"!-- 中部横幅广告位 -->\n";
OA_output['3'] += "<"+"ins class=\"adsbygoogle\"\n";
OA_output['3'] += "style=\"display:inline-block;width:728px;height:90px\"\n";
OA_output['3'] += "data-ad-client=\"ca-pub-6330872677300335\"\n";
OA_output['3'] += "data-ad-slot=\"5598290435\"><"+"/ins>\n";
OA_output['3'] += "<"+"script>\n";
OA_output['3'] += "(adsbygoogle = window.adsbygoogle || []).push({});\n";
OA_output['3'] += "<"+"/script><"+"div id=\'beacon_df4fafc5e8\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=2&amp;campaignid=1&amp;zoneid=3&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=df4fafc5e8\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div><"+"/div>\n";
OA_output['4'] = '';
OA_output['4'] += "<"+"div id=\'beacon_b5427e0f4c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=4&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=b5427e0f4c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['5'] = '';
OA_output['5'] += "<"+"div id=\'beacon_10aafbb4cf\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=5&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=10aafbb4cf\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['6'] = '';
OA_output['6'] += "<"+"div id=\'beacon_6cc72f7014\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=6&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=6cc72f7014\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['7'] = '';
OA_output['7'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=57__zoneid=7__cb=0da58f96fb__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011387052\' target=\'_blank\'><"+"strong> Java 微服务实践课<"+"/strong><"+"br>\n";
OA_output['7'] += "<"+"small style=\"color: #999\">上千人学习过的微服务实栈课<"+"/small><"+"/a><"+"div id=\'beacon_0da58f96fb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=57&amp;campaignid=14&amp;zoneid=7&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=0da58f96fb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['9'] = '';
OA_output['9'] += "<"+"a href=\'https://sponsor.segmentfault.com/ck.php?oaparams=2__bannerid=56__zoneid=9__cb=ea5dd6bdee__oadest=https%3A%2F%2Fsegmentfault.com%2Fls%2F1650000011318558\' target=\'_blank\'><"+"strong>大神的PHP 进阶之路<"+"/strong><"+"br>\n";
OA_output['9'] += "<"+"small style=\"color: #999\">亿级 PV 项目的架构梳理，性能提升实战<"+"/small><"+"/a><"+"div id=\'beacon_ea5dd6bdee\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=56&amp;campaignid=14&amp;zoneid=9&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=ea5dd6bdee\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['10'] = '';
OA_output['10'] += "<"+"div id=\'beacon_230bcc8e30\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=10&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=230bcc8e30\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['11'] = '';
OA_output['11'] += "<"+"div id=\'beacon_49ced24a2f\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=11&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=49ced24a2f\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['12'] = '';
OA_output['12'] += "<"+"div id=\'beacon_0d8a434669\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=12&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=0d8a434669\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['13'] = '';
OA_output['13'] += "<"+"div id=\'beacon_bbf09fccfb\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=13&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=bbf09fccfb\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['14'] = '';
OA_output['14'] += "<"+"div id=\'beacon_aacaa0d108\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=14&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=aacaa0d108\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['15'] = '';
OA_output['15'] += "<"+"div id=\'beacon_6a68b12e19\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=15&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=6a68b12e19\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['16'] = '';
OA_output['16'] += "<"+"div id=\'beacon_b8b45baf6d\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=16&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=b8b45baf6d\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
OA_output['17'] = '';
OA_output['17'] += "<"+"div id=\'beacon_698e43db3c\' style=\'position: absolute; left: 0px; top: 0px; visibility: hidden;\'><"+"img src=\'https://sponsor.segmentfault.com/lg.php?bannerid=0&amp;campaignid=0&amp;zoneid=17&amp;loc=https%3A%2F%2Fsegmentfault.com%2Fa%2F1190000020982687&amp;cb=698e43db3c\' width=\'0\' height=\'0\' alt=\'\' style=\'width: 0px; height: 0px;\' /><"+"/div>\n";
